---
title: Class Diagram OBD
---
classDiagram
  %% Relationtships
  User <|-- Premium

  namespace Users {

    class New_User {
      create_account()
    }

    class User {
      - String name
      - String surname
      - String last_name
      - String email
      - String passwd

      %% Account Managment
      + log_in()
      + sign_out()
      + change_passwd()
      + recover_passwd()
      + delete_account()
      + suspend_account()

      %% Functionalities
      + pair_obd()
      + scan_auto()
      + view_last_log()
    }

    class Premium {
      + advanced_scan_auto()
      + get_car_docs()
      + view_logs()
      %% NOTE: We could implement IA
      + fix_docs()
    }
  }

  namespace Obd {
    class Code {
      - String code
      - String group
      - String suffix

      + get_code()
      %% TODO: Rename set_group_and_code() for validate_code()
      - validate_code()
      + get_code_description()
    }

    class Connection {
      + connect()
      + disconnect()
    }
}

